sonar.projectKey=aboubakertounli_DevSecOps-x-GitOps
sonar.organization=aboubakertounli
sonar.sources=src
sonar.tests=test
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
